# Generated by Django 1.9.2 on 2016-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_auto_20160206_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingaccount",
            name="subscribe_to_newsletter",
            field=models.BooleanField(default=False, verbose_name="Subscribe to email newsletter"),
        ),
    ]
