# Generated by Django 1.9.2 on 2016-02-15 21:01

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_auto_20160215_2052"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address_city",
            field=models.CharField(default="", max_length=255, verbose_name="town/city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="address_country",
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="booking",
            name="address_county",
            field=models.CharField(blank=True, max_length=255, verbose_name="county/state"),
        ),
        migrations.AddField(
            model_name="booking",
            name="address_line1",
            field=models.CharField(default="", max_length=255, verbose_name="address line 1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_city",
            field=models.CharField(default="", max_length=255, verbose_name="town/city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_country",
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_county",
            field=models.CharField(blank=True, max_length=255, verbose_name="county/state"),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_line1",
            field=models.CharField(default="", max_length=255, verbose_name="address line 1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_line2",
            field=models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
        ),
        migrations.AddField(
            model_name="booking",
            name="gp_city",
            field=models.CharField(default="", max_length=255, verbose_name="town/city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="gp_country",
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="booking",
            name="gp_county",
            field=models.CharField(blank=True, max_length=255, verbose_name="county/state"),
        ),
        migrations.AddField(
            model_name="booking",
            name="gp_line1",
            field=models.CharField(default="", max_length=255, verbose_name="address line 1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="gp_line2",
            field=models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
        ),
    ]
