# Generated by Django 1.10.3 on 2016-11-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0027_migrate_to_payment_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="origin_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="origin_type",
        ),
    ]
