# Generated by Django 1.11.1 on 2018-04-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20170410_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaccount',
            name='subscribe_to_mailings',
            field=models.NullBooleanField(default=None, verbose_name='Receive mailings about future camps'),
        ),
        migrations.AlterField(
            model_name='bookingaccount',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=False, help_text="Your email address will be registered with a newsletter service, <a href='https://mailchimp.com/'>MailChimp</a>, if this is selected.", verbose_name='Subscribe to email newsletter'),
        ),
    ]
