# Generated by Django 1.11.1 on 2018-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0030_auto_20180406_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccount",
            name="subscribe_to_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="<span class='mailchimp-notice'>We use a third party email service provider,\nMailChimp, to send you these newsletter emails. We provide MailChimp with only\nyour email address. MailChimp treats information about you in accordance with\nthe provisions of its <a href='https://mailchimp.com/legal/privacy/'>Privacy\nPolicy</a>. MailChimp also utilizes certain technologies, such as pixels and web\nbeacons, in the emails that are sent through MailChimp. These technologies allow\nMailChimp to track whether you have opened or clicked on our emails and if so,\nthe date, time, and IP address associated with the open and/or click. For more\ninformation on MailChimp's use of these technologies, you can read their <a\nhref='https://mailchimp.com/legal/cookies/'>Cookie Statement</a>.</span>",
                verbose_name="Subscribe to email newsletter",
            ),
        ),
    ]
