# Generated by Django 3.1.5 on 2021-02-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_auto_20210204_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_tetanus_injection',
            new_name='last_tetanus_injection_date',
        ),
    ]
