# Generated by Django 3.1.7 on 2021-04-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0036_bookingaccount_created"),
    ]

    operations = [
        migrations.RunSQL(
            """
        -- Populate 'created'.
        -- For online created records, it's easy:
        UPDATE bookings_bookingaccount
        SET created = first_login
        WHERE created IS NULL;

        -- Otherwise
        -- Guess using Booking
        UPDATE bookings_bookingaccount
        SET created = (SELECT created FROM bookings_booking
                       WHERE account_id = bookings_bookingaccount.id
                       ORDER BY created ASC
                       LIMIT 1)
        WHERE created IS NULL;

        -- Guess using Payment
        UPDATE bookings_bookingaccount
        SET created = (SELECT created FROM bookings_payment
                       WHERE account_id = bookings_bookingaccount.id
                       ORDER BY created ASC
                       LIMIT 1)
        WHERE created IS NULL;

        -- No info. Make a guess using `created` of next record
        UPDATE bookings_bookingaccount a
        SET created = (SELECT created FROM bookings_bookingaccount b
                       WHERE b.id > a.id AND b.created IS NOT NULL
                       ORDER BY created ASC
                       LIMIT 1)
        WHERE created IS NULL;

        -- Fallback
        UPDATE bookings_bookingaccount
        SET created = now()
        WHERE created IS NULL;
        """,
            "",
        )
    ]
