# Generated by Django 3.1.7 on 2021-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0047_auto_20210611_0928"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="publicity_photos_agreement",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
