# Generated by Django 3.2.6 on 2021-10-06 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import cciw.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0050_auto_20210818_1235"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteOffDebt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_off_debt",
                        to="bookings.bookingaccount",
                    ),
                ),
            ],
            bases=(cciw.bookings.models.NoEditMixin, models.Model),
        ),
        migrations.AddField(
            model_name="paymentsource",
            name="write_off_debt",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bookings.writeoffdebt"
            ),
        ),
    ]
