# Generated by Django 3.2.6 on 2021-10-11 18:10

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import cciw.documents.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0052_alter_writeoffdebt_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportingInformationDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("filename", models.CharField(max_length=255)),
                ("mimetype", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("content", models.BinaryField()),
            ],
            options={
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="SupportingInformationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupportingInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_received", models.DateField(default=datetime.date.today)),
                (
                    "from_name",
                    models.CharField(
                        help_text="Name of person or organisation the information is from", max_length=100
                    ),
                ),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("from_telephone", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supporting_information_records",
                        to="bookings.booking",
                    ),
                ),
                (
                    "document",
                    cciw.documents.fields.DocumentField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supporting_information",
                        to="bookings.supportinginformationdocument",
                    ),
                ),
                (
                    "information_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bookings.supportinginformationtype"
                    ),
                ),
            ],
            options={
                "verbose_name": "supporting information record",
                "verbose_name_plural": "supporting information records",
            },
        ),
    ]
