# Generated by Django 3.2.6 on 2021-10-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0053_supporting_information"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="writeoffdebt",
            options={
                "base_manager_name": "objects",
                "verbose_name": "write-off debt record",
                "verbose_name_plural": "write-off debt records",
            },
        ),
    ]
