# Generated by Django 3.2.6 on 2021-10-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0054_alter_writeoffdebt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportinginformation",
            name="erased_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="supportinginformationdocument",
            name="erased_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
