# Generated by Django 4.0.3 on 2022-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0055_auto_20211015_0050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaccount",
            name="subscribe_to_newsletter",
            field=models.BooleanField(default=False, verbose_name="Subscribe to email newsletter"),
        ),
    ]
