# Generated by Django 4.2.5 on 2024-03-30 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_squashed_0057_default_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="erased_on",
            new_name="erased_at",
        ),
        migrations.RenameField(
            model_name="bookingaccount",
            old_name="erased_on",
            new_name="erased_at",
        ),
        migrations.RenameField(
            model_name="supportinginformation",
            old_name="erased_on",
            new_name="erased_at",
        ),
        migrations.RenameField(
            model_name="supportinginformationdocument",
            old_name="erased_on",
            new_name="erased_at",
        ),
    ]
