# Generated by Django 4.2.5 on 2024-03-30 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0058_rename_erased_on_booking_erased_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking_expires",
            new_name="booking_expires_at",
        ),
    ]
