# Generated by Django 4.2.5 on 2024-03-30 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0059_rename_booking_expires_booking_booking_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="date_of_birth",
            new_name="birth_date",
        ),
    ]
