# Generated by Django 4.2.5 on 2024-03-30 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0061_alter_booking_birth_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingaccount",
            old_name="first_login",
            new_name="first_login_at",
        ),
    ]
