# Generated by Django 4.2.5 on 2024-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0062_rename_first_login_bookingaccount_first_login_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingaccount",
            old_name="last_login",
            new_name="last_login_at",
        ),
    ]
