# Generated by Django 4.2.5 on 2024-03-30 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0063_rename_last_login_bookingaccount_last_login_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingaccount",
            old_name="last_payment_reminder",
            new_name="last_payment_reminder_at",
        ),
    ]
