# Generated by Django 4.2.5 on 2024-03-30 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0064_rename_last_payment_reminder_bookingaccount_last_payment_reminder_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="processed",
            new_name="processed_at",
        ),
    ]
