# Generated by Django 4.2.5 on 2024-03-30 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0065_rename_processed_payment_processed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supportinginformation",
            old_name="date_received",
            new_name="received_on",
        ),
    ]
