# Generated by Django 4.2.5 on 2024-03-30 20:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0066_rename_date_received_supportinginformation_received_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportinginformation",
            name="received_on",
            field=models.DateField(default=datetime.date.today, verbose_name="date received"),
        ),
    ]
