# Generated by Django 5.0.9 on 2025-02-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0067_alter_supportinginformation_received_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="friends_for_tent_sharing",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
