# Generated by Django 5.2.1 on 2025-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0068_booking_friends_for_tent_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="state_new",
            field=models.CharField(
                choices=[
                    ("info_complete", "Information complete"),
                    ("approved", "Manually approved"),
                    ("booked", "Booked"),
                    ("cancelled_deposit_kept", "Cancelled - deposit kept"),
                    ("cancelled_half_refund", "Cancelled - half refund (pre 2015 only)"),
                    ("cancelled_full_refund", "Cancelled - full refund"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
