# Generated by Django 5.2.1 on 2025-10-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0069_booking_state_new"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE bookings_booking SET state_new = 'info_complete'  WHERE state = 0 ;
            UPDATE bookings_booking SET state_new = 'approved' WHERE state = 1 ;
            UPDATE bookings_booking SET state_new = 'booked' WHERE state = 2 ;
            UPDATE bookings_booking SET state_new = 'cancelled_deposit_kept' WHERE state = 3 ;
            UPDATE bookings_booking SET state_new = 'cancelled_half_refund' WHERE state = 4 ;
            UPDATE bookings_booking SET state_new = 'cancelled_full_refund' WHERE state = 5 ;
            """,
            "",
            elidable=True,
        ),
    ]
