# Generated by Django 5.2.1 on 2025-10-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0070_auto_20251016_0745"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="state",
        ),
    ]
