# Generated by Django 5.2.1 on 2025-10-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0071_remove_booking_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="state_new",
            new_name="state",
        ),
    ]
