# Generated by Django 5.2.1 on 2025-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0072_rename_state_new_booking_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("info_complete", "Information complete"),
                    ("approved", "Manually approved"),
                    ("booked", "Booked"),
                    ("cancelled_deposit_kept", "Cancelled - deposit kept"),
                    ("cancelled_half_refund", "Cancelled - half refund (pre 2015 only)"),
                    ("cancelled_full_refund", "Cancelled - full refund"),
                ],
                help_text="<ul><li>To book, set to 'Booked' <b>and</b> ensure 'Booking expires' is empty</li><li>For people paying online who have been stopped (e.g. due to having a custom discount or serious illness or child too young etc.), set to 'Manually approved' to allow them to book and pay</li><li>If there are queries before it can be booked, set to 'Information complete'</li></ul>",
            ),
        ),
    ]
