# Generated by Django 5.2.7 on 2025-11-13 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0074_bookingapproval"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookingapproval",
            unique_together={("booking", "type")},
        ),
    ]
