# Generated by Django 5.2.7 on 2025-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0075_alter_bookingapproval_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingapproval",
            old_name="approved_at",
            new_name="checked_at",
        ),
        migrations.RenameField(
            model_name="bookingapproval",
            old_name="approved_by",
            new_name="checked_by",
        ),
        migrations.AddField(
            model_name="bookingapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                ],
                default="pending",
            ),
        ),
    ]
