# Generated by Django 5.2.7 on 2025-11-15 20:18

from django.db import migrations


def forwards(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(state="approved").update(state="info_complete")


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0076_rename_approved_at_bookingapproval_checked_at_and_more"),
    ]

    operations = [migrations.RunPython(forwards, backwards, elidable=True)]
