# Generated by Django 5.2.7 on 2025-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0078_alter_booking_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                (
                    "bookings_open_for_entry_on",
                    models.DateField(
                        help_text="The date that people can start to fill in booking details",
                        verbose_name="open for data entry",
                    ),
                ),
                (
                    "bookings_open_for_booking_at",
                    models.DateTimeField(
                        help_text="The date that we allow people to press 'Book'",
                        verbose_name="open for booking",
                    ),
                ),
            ],
        ),
    ]
