# Generated by Django 5.2.7 on 2025-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0079_yearconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearconfig",
            name="bookings_open_for_booking_at",
        ),
        migrations.AddField(
            model_name="yearconfig",
            name="bookings_close_for_initial_period",
            field=models.DateField(
                default=None,
                help_text="The last date of the initial booking period. Bookings made on and before this date are considered together.",
                verbose_name="close initial booking period",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yearconfig",
            name="bookings_open_for_booking_on",
            field=models.DateField(
                default=None,
                help_text="The date that we allow people to press 'Book'",
                verbose_name="open for booking",
            ),
            preserve_default=False,
        ),
    ]
