# Generated by Django 5.2.7 on 2025-12-04 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0080_remove_yearconfig_bookings_open_for_booking_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_expires_at",
        ),
    ]
