# Generated by Django 5.2.7 on 2025-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0081_remove_booking_booking_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("info_complete", "Information complete"),
                    ("booked", "Booked"),
                    ("cancelled_deposit_kept", "Cancelled - deposit kept"),
                    (
                        "cancelled_half_refund",
                        "Cancelled - half refund (pre 2015 only)",
                    ),
                    ("cancelled_full_refund", "Cancelled - full refund"),
                ]
            ),
        ),
    ]
