# Generated by Django 6.0 on 2025-12-06 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0082_alter_booking_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingQueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("accepted", "Accepted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="waiting",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entry",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "queue entry",
                "verbose_name_plural": "queue entries",
            },
        ),
    ]
