# Generated by Django 6.0 on 2025-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0083_bookingqueueentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="officer_child",
            field=models.BooleanField(default=False),
        ),
    ]
