# Generated by Django 6.0 on 2025-12-14 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0084_bookingqueueentry_officer_child"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yearconfig",
            old_name="bookings_close_for_initial_period",
            new_name="bookings_close_for_initial_period_on",
        ),
    ]
