# Generated by Django 6.0 on 2025-12-14 19:26

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookings",
            "0085_rename_bookings_close_for_initial_period_yearconfig_bookings_close_for_initial_period_on",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="fuzzy_camper_id",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.text.Trim(
                            django.db.models.functions.text.Replace(
                                django.db.models.functions.text.Concat("first_name", models.Value(" "), "last_name"),
                                models.Value("  "),
                                models.Value(" "),
                            )
                        )
                    ),
                    models.Value(" "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear("birth_date"),
                        output_field=models.CharField(),
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
    ]
