# Generated by Django 6.0 on 2025-12-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0086_booking_fuzzy_camper_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="first_timer_allocated",
            field=models.BooleanField(default=False),
        ),
    ]
