# Generated by Django 6.0 on 2025-12-14 19:33

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0087_bookingqueueentry_first_timer_allocated"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="sibling_booking_account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookings.bookingaccount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingqueueentry",
            name="sibling_surname",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingqueueentry",
            name="sibling_fuzzy_id",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.text.Lower("sibling_surname"),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        "sibling_booking_account_id", output_field=models.CharField()
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
    ]
