# Generated by Django 6.0 on 2025-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0088_bookingqueueentry_sibling_booking_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="erased_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
