# Generated by Django 6.0 on 2025-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0089_bookingqueueentry_erased_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingqueueentry",
            name="state",
        ),
        migrations.AddField(
            model_name="bookingqueueentry",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
