# Generated by Django 6.0 on 2025-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0091_queueentryactionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="enqueued_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
