# Generated by Django 6.0 on 2025-12-18 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0092_bookingqueueentry_enqueued_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE bookings_bookingqueueentry SET enqueued_at = created_at WHERE enqueued_at IS NULL;
    """,
            "",
        )
    ]
