# Generated by Django 6.0 on 2025-12-18 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0093_populate_enqueued_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingqueueentry",
            name="enqueued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
