# Generated by Django 6.0 on 2025-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0094_alter_bookingqueueentry_enqueued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearconfig",
            name="bookings_initial_notifications_on",
            field=models.DateField(
                default=None,
                help_text="The date we will have sent initial notifications about bookings, after the initial booking period",
                verbose_name="send initial bookings notifications",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="yearconfig",
            name="payments_due_on",
            field=models.DateField(
                default=None,
                help_text="The date we expect payment for places to be made (unless a payment plan is agreed on)",
            ),
            preserve_default=False,
        ),
    ]
