# Generated by Django 6.0 on 2025-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0095_yearconfig_bookings_initial_notifications_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="accepted_notification_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bookingqueueentry",
            name="declined_notification_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
