# Generated by Django 6.0.1 on 2026-01-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0096_bookingqueueentry_accepted_notification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearconfig",
            name="cancellations_full_refund_cutoff_on",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="The last date people can cancel bookings and still get a full refund",
                null=True,
            ),
        ),
    ]
