# Generated by Django 6.0.1 on 2026-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0097_yearconfig_cancellations_full_refund_cutoff_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price_type_new",
            field=models.CharField(
                choices=[
                    ("full", "Full price"),
                    ("second_child", "2nd child discount"),
                    ("third_child", "3rd child discount"),
                    ("custom_discount", "Custom discount"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="price_type_new",
            field=models.CharField(
                choices=[
                    ("full", "Full price"),
                    ("second_child", "2nd child discount"),
                    ("third_child", "3rd child discount"),
                    (
                        "south_wales_transport",
                        "South wales transport surcharge (pre 2015)",
                    ),
                    ("deposit", "Deposit"),
                    ("early_bird_discount", "Early bird discount"),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
