# Generated by Django 6.0.1 on 2026-01-09 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0098_booking_price_type_new_price_price_type_new"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE bookings_booking SET price_type_new = 'full' WHERE price_type = 0 ;
UPDATE bookings_booking SET price_type_new = 'second_child' WHERE price_type = 1;
UPDATE bookings_booking SET price_type_new = 'third_child' WHERE price_type = 2;
UPDATE bookings_booking SET price_type_new = 'custom_discount' WHERE price_type = 3;
UPDATE bookings_booking SET price_type_new = 'south_wales_transport' WHERE price_type = 4;
UPDATE bookings_booking SET price_type_new = 'deposit' WHERE price_type = 5;
UPDATE bookings_booking SET price_type_new = 'early_bird_discount' WHERE price_type = 6;

UPDATE bookings_price SET price_type_new = 'full' WHERE price_type = 0 ;
UPDATE bookings_price SET price_type_new = 'second_child' WHERE price_type = 1;
UPDATE bookings_price SET price_type_new = 'third_child' WHERE price_type = 2;
UPDATE bookings_price SET price_type_new = 'custom_discount' WHERE price_type = 3;
UPDATE bookings_price SET price_type_new = 'south_wales_transport' WHERE price_type = 4;
UPDATE bookings_price SET price_type_new = 'deposit' WHERE price_type = 5;
UPDATE bookings_price SET price_type_new = 'early_bird_discount' WHERE price_type = 6;
            """,
            "",
            elidable=True,
        ),
    ]
