# Generated by Django 6.0.1 on 2026-01-09 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0099_migrate_price_type_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="price_type",
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("year", "price_type_new")},
        ),
        migrations.RemoveField(
            model_name="price",
            name="price_type",
        ),
    ]
