# Generated by Django 6.0.1 on 2026-01-09 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0100_remove_booking_price_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="price_type_new",
            new_name="price_type",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="price_type_new",
            new_name="price_type",
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("year", "price_type")},
        ),
    ]
