# Generated by Django 6.0.1 on 2026-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0101_rename_price_type_new_booking_price_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("full", "Full price"),
                    ("second_child", "2nd child discount"),
                    ("third_child", "3rd child discount"),
                    (
                        "south_wales_transport",
                        "South wales transport surcharge (pre 2015)",
                    ),
                    ("deposit", "Deposit"),
                    ("early_bird_discount", "Early bird discount"),
                    ("booking_fee", "Booking fee"),
                ]
            ),
        ),
    ]
