# Generated by Django 6.0.1 on 2026-01-10 08:15

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0103_booking_fuzzy_camper_id_strict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="fuzzy_camper_id",
            field=models.GeneratedField(
                db_index=True,
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.text.Trim(
                            django.db.models.functions.text.Replace(
                                django.db.models.functions.text.Concat("first_name", models.Value(" "), "last_name"),
                                models.Value("  "),
                                models.Value(" "),
                            )
                        )
                    ),
                    models.Value(" "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear("birth_date"),
                        output_field=models.CharField(),
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="fuzzy_camper_id_strict",
            field=models.GeneratedField(
                db_index=True,
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.comparison.Cast("account_id", output_field=models.CharField()),
                    models.Value(" "),
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.text.Trim(
                            django.db.models.functions.text.Replace(
                                django.db.models.functions.text.Concat("first_name", models.Value(" "), "last_name"),
                                models.Value("  "),
                                models.Value(" "),
                            )
                        )
                    ),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.ExtractYear("birth_date"),
                        output_field=models.CharField(),
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
    ]
