# Generated by Django 6.0.1 on 2026-01-10 08:18

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0104_alter_booking_fuzzy_camper_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingqueueentry",
            name="sibling_fuzzy_id",
            field=models.GeneratedField(
                db_index=True,
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.text.Lower("sibling_surname"),
                    models.Value("-"),
                    django.db.models.functions.comparison.Cast(
                        "sibling_booking_account_id", output_field=models.CharField()
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
    ]
