# Generated by Django 6.0.1 on 2026-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0105_alter_bookingqueueentry_sibling_fuzzy_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="fuzzy_camper_id_strict",
        ),
    ]
