# Generated by Django 6.0.1 on 2026-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0107_booking_fuzzy_camper_id_strict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="shelved",
            field=models.BooleanField(default=False, help_text="Used by user to put in 'Saved for later'"),
        ),
    ]
