# Generated by Django 6.0.1 on 2026-01-12 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0108_alter_booking_shelved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queueentryactionlog",
            old_name="user",
            new_name="staff_user",
        ),
    ]
