# Generated by Django 6.0.1 on 2026-01-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0110_alter_queueentryactionlog_staff_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentryactionlog",
            name="account_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The booking account that triggered the action",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_entry_actions_performed",
                to="bookings.bookingaccount",
            ),
        ),
        migrations.AlterField(
            model_name="queueentryactionlog",
            name="staff_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The staff user that triggered the action",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_entry_actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
