# Generated by Django 6.0.1 on 2026-01-12 17:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0111_queueentryactionlog_account_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentryactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("fields_changed", "fields changed"),
                    ("created", "created"),
                    ("allocated", "allocated"),
                    ("declined", "declined"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="queueentryactionlog",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
