# Generated by Django 6.0.1 on 2026-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0112_alter_queueentryactionlog_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingqueueentry",
            name="waiting_list_from_start",
            field=models.BooleanField(default=False),
        ),
    ]
