# Generated by Django 6.0.1 on 2026-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0113_bookingqueueentry_waiting_list_from_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("full", "Full price"),
                    ("second_child", "2nd child discount"),
                    ("third_child", "3rd child discount"),
                    ("deposit", "Deposit"),
                    ("early_bird_discount", "Early bird discount"),
                    ("booking_fee", "Booking fee"),
                ]
            ),
        ),
    ]
