# Generated by Django 6.0.1 on 2026-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0114_alter_price_price_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("full", "Full price"),
                    ("second_child", "2nd child discount"),
                    ("third_child", "3rd child discount"),
                    ("deposit", "Deposit"),
                    ("booking_fee", "Booking fee"),
                ]
            ),
        ),
    ]
