# Generated by Django 6.0.1 on 2026-01-15 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0115_alter_price_price_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomAgreement",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="custom_agreements_checked",
        ),
    ]
