# Generated by Django 6.0.1 on 2026-01-15 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0116_delete_customagreement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queueentryactionlog",
            options={"ordering": ("created_at",)},
        ),
    ]
