# Generated by Django 6.0.1 on 2026-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0117_alter_queueentryactionlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="If not empty, a 'Booked' booking will expire at this time",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("info_complete", "Information complete"),
                    ("booked", "Booked"),
                    (
                        "cancelled_deposit_kept",
                        "Cancelled - deposit kept (pre 2026 only)",
                    ),
                    ("cancelled_booking_fee_kept", "Cancelled - booking fee kept"),
                    ("cancelled_half_refund", "Cancelled - half refund"),
                    ("cancelled_full_refund", "Cancelled - full refund"),
                ]
            ),
        ),
    ]
