# Generated by Django 6.0.1 on 2026-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0118_booking_booking_expires_at_alter_booking_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentryactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("fields_changed", "fields changed"),
                    ("created", "created"),
                    ("allocated", "allocated"),
                    ("declined", "declined"),
                    ("accepted", "accepted"),
                    ("rejected_offered_place", "rejected offered place"),
                    ("expired", "expired"),
                ]
            ),
        ),
    ]
