# Generated by Django 6.0.1 on 2026-03-02 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0119_alter_queueentryactionlog_action_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="fuzzy_camper_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="fuzzy_camper_id_strict",
        ),
    ]
