# Generated by Django 6.0.5 on 2026-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0121_booking_fuzzy_camper_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="age_on_camp",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
