# Generated by Django 6.0.5 on 2026-08-09 20:37
from datetime import date

from dateutil.relativedelta import relativedelta
from django.db import migrations


def forwards(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.filter(age_on_camp__isnull=True):
        age_base_date = date(booking.camp.year, 8, 31)
        booking.age_on_camp = relativedelta(age_base_date, booking.birth_date).years
        booking.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0122_booking_age_on_camp"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
