# Generated by Django 6.0.5 on 2026-08-09 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0123_populate_age_on_camp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="age_on_camp",
            new_name="stored_age_on_camp",
        ),
    ]
