# Generated by Django 6.0.5 on 2026-08-09 22:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0124_rename_age_on_camp_booking_stored_age_on_camp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="age_on_camp",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.F("stored_age_on_camp"),
                output_field=models.IntegerField(),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="populate_stored_age_on_camp",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                NEW.stored_age_on_camp = COALESCE(\n                   (SELECT EXTRACT(YEAR FROM\n                      age(\n                        make_date(\n                          (SELECT year\n                              FROM cciwmain_camp AS camp\n                              JOIN bookings_booking AS booking\n                              ON booking.camp_id = camp.id\n                              WHERE booking.id = NEW.id limit 1),\n                           8, 31),\n                        NEW.birth_date)\n                      )\n                    ),\n                    NEW.stored_age_on_camp\n                );\n                RETURN NEW;\n                ",
                    hash="1e8f4bbcd2763a86c219e0d4f7c1925b942b8625",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_populate_stored_age_on_camp_e9658",
                    table="bookings_booking",
                    when="BEFORE",
                ),
            ),
        ),
    ]
