# Generated by Django 6.0.5 on 2026-08-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0125_booking_age_on_camp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
    ]
