# Generated by Django 6.0.5 on 2026-08-09 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0126_alter_booking_birth_date"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE bookings_booking SET birth_date = NULL WHERE erased_at IS NOT NULL;
    """,
            "",
        )
    ]
