# Generated by Django 6.0.5 on 2026-08-09 22:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0127_null_out_old_booking_birth_date"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="booking",
            name="populate_stored_age_on_camp",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="populate_stored_age_on_camp",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                NEW.stored_age_on_camp = COALESCE(\n                   (SELECT EXTRACT(YEAR FROM\n                      age(\n                        make_date(\n                          (SELECT year\n                              FROM cciwmain_camp AS camp\n                              WHERE camp.id = NEW.camp_id\n                              LIMIT 1),\n                           8, 31),\n                        NEW.birth_date)\n                      )\n                    ),\n                    NEW.stored_age_on_camp,\n                    OLD.stored_age_on_camp\n                );\n                RETURN NEW;\n                ",
                    hash="ff407d5bd13690b2e14dcccd803bae1e35926033",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_populate_stored_age_on_camp_e9658",
                    table="bookings_booking",
                    when="BEFORE",
                ),
            ),
        ),
    ]
