# Generated by Django 6.0.5 on 2026-08-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0128_remove_booking_populate_stored_age_on_camp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="stored_age_on_camp",
            field=models.IntegerField(),
        ),
    ]
