# Generated by Django 6.0.5 on 2026-08-14 17:24

from django.db import migrations


def forwards(apps, schema_editor):
    BookingAccount = apps.get_model("bookings", "BookingAccount")
    ScheduledMailRecord = apps.get_model("mail", "ScheduledMailRecord")
    for account in BookingAccount.objects.filter(last_payment_reminder_at__isnull=False):
        ScheduledMailRecord.objects.create(
            tracking_id=f"booking-account-payment-reminder-{account.id}",
            last_sent_at=account.last_payment_reminder_at,
            sent_count=1,  # Don't know for sure, it's at least 1
        )


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0129_alter_booking_stored_age_on_camp"),
        ("mail", "0008_initial"),
    ]

    operations = [migrations.RunPython(forwards)]
