# Generated by Django 6.0.5 on 2026-08-14 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0130_preserve_booking_account_last_payment_reminder_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingaccount",
            name="last_payment_reminder_at",
        ),
    ]
