# Generated by Django 4.0.7 on 2022-10-15 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_squashed_0014_auto_20210818_1235"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cciwmain", "0001_squashed_0024_auto_20210818_1235"),
        ("officers", "0002_invitation"),
    ]

    # Hack to make sure this migration isn't applied
    replaces = [
        ("cciwmain", "0024_auto_20210818_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="officers",
            field=models.ManyToManyField(through="officers.Invitation", to=settings.AUTH_USER_MODEL),
        ),
    ]
