# Generated by Django 6.0 on 2025-12-11 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cciwmain", "0002_camp_officers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campname",
            options={"ordering": ("name",)},
        ),
    ]
