# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cciwmain', '0018_campname_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'base_manager_name': 'objects', 'ordering': ['-year', 'start_date']},
        ),
    ]
