[tool.black]
line-length = 120
# required-version = '22.1.0' # see https://github.com/psf/black/issues/2493
target-version = ['py39']


[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
skip_glob = ['**/migrations/*.py']
known_third_party = ['django-wiki', 'django-functest', 'fabric', 'paramiko']
known_first_party = 'cciw'
skip = ['settings.py', 'node_modules', '.git']


[tool.mypy]
ignore_missing_imports = true
plugins = ['pydantic.mypy']
