# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # For unknown reason, uncommenting this causes tests to fail to run with
        # django.db.migrations.exceptions.NodeNotFoundError: Migration contact_us.0001_initial dependencies reference nonexistent parent node ...
        # although the migration runs fine manually.
        #('bookings', '0031_auto_20180513_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.BookingAccount')),
            ],
        ),
    ]
