# Generated by Django 4.0.7 on 2022-10-15 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("contact_us", "0001_initial"),
        ("contact_us", "0002_auto_20190801_2019"),
        ("contact_us", "0003_auto_20210506_0806"),
        ("contact_us", "0004_alter_message_id"),
        ("contact_us", "0005_message_subject"),
        ("contact_us", "0006_contact_us_bogofilter"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email address")),
                ("name", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.bookingaccount",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("website", "Web site problems"),
                            ("bookingform", "Paper booking form request"),
                            ("bookings", "Camp bookings and places"),
                            ("data_protection", "Data protection and related"),
                            ("volunteering", "Volunteering"),
                            ("general", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("bogosity", models.FloatField(blank=True, default=None, null=True)),
                (
                    "spam_classification_bogofilter",
                    models.CharField(
                        choices=[
                            ("HAM", "Ham"),
                            ("SPAM", "Spam"),
                            ("UNSURE", "Unsure"),
                            ("ERROR", "Error"),
                            ("UNCLASSIFIED", "Unclassified"),
                        ],
                        default="UNCLASSIFIED",
                        max_length=12,
                        verbose_name="Bogofilter status",
                    ),
                ),
                (
                    "spam_classification_manual",
                    models.CharField(
                        choices=[("HAM", "Ham"), ("SPAM", "Spam"), ("UNCLASSIFIED", "Unclassified")],
                        default="UNCLASSIFIED",
                        max_length=12,
                        verbose_name="Marked spam",
                    ),
                ),
            ],
        ),
    ]
