# Generated by Django 3.1.7 on 2021-05-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0002_auto_20190801_2019"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
