# Generated by Django 6.0.1 on 2026-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0001_squashed_0006_contact_us_bogofilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                choices=[
                    ("bookings", "Camp bookings and places"),
                    ("bookingform", "Paper booking form request"),
                    ("website", "Web site problems"),
                    ("data_protection", "Data protection and related"),
                    ("volunteering", "Volunteering"),
                    ("general", "Other"),
                ],
                max_length=15,
            ),
        ),
    ]
