from cciw.cciwmain.tests.camps import *
from cciw.cciwmain.tests.members import *
from cciw.cciwmain.tests.forums import *
from cciw.cciwmain.tests.news import *
from cciw.cciwmain.tests.htmlchunks import *
from cciw.cciwmain.tests.sites import *
from cciw.cciwmain.tests.decorators import *
from cciw.cciwmain.tests.contact import *
from cciw.cciwmain.tests.bbcode import *
