# Generated by Django 4.0.7 on 2022-10-15 15:01

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("officers", "0001_squashed_0066_alter_reference_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_added", models.DateField(default=datetime.date.today)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="cciwmain.camp"
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-camp__year", "officer__first_name", "officer__last_name"),
                "base_manager_name": "objects",
                "unique_together": {("officer", "camp")},
            },
        ),
    ]
