# Generated by Django 4.0.7 on 2022-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0003_camprole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camprole",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
