# Generated by Django 4.0.7 on 2022-11-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0005_populate_camp_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camprole",
            options={"ordering": ["name"]},
        ),
    ]
