# Generated by Django 4.0.7 on 2022-11-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0006_alter_camprole_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="officers.camprole",
            ),
        ),
    ]
