# Generated by Django 4.2.3 on 2023-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0008_alter_application_officer_alter_dbsactionlog_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referenceaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("requested", "Reference requested"),
                    ("received", "Reference received"),
                    ("filledin", "Reference filled in manually"),
                    ("nag", "Applicant nagged"),
                    ("detailscorrected", "Referee details corrected"),
                ],
                max_length=20,
            ),
        ),
    ]
