# Generated by Django 4.2.5 on 2024-03-30 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0009_alter_referenceaction_action_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="erased_on",
            new_name="erased_at",
        ),
    ]
