# Generated by Django 4.2.5 on 2024-03-30 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0010_rename_erased_on_application_erased_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "base_manager_name": "objects",
                "ordering": ("-saved_on", "officer__first_name", "officer__last_name"),
            },
        ),
        migrations.AlterModelOptions(
            name="referee",
            options={
                "ordering": (
                    "application__saved_on",
                    "application__officer__first_name",
                    "application__officer__last_name",
                    "referee_number",
                )
            },
        ),
        migrations.RenameField(
            model_name="application",
            old_name="date_saved",
            new_name="saved_on",
        ),
    ]
