# Generated by Django 4.2.5 on 2024-03-30 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0012_rename_completed_dbscheck_completed_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="date_added",
            new_name="added_on",
        ),
    ]
