# Generated by Django 4.2.5 on 2024-03-30 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0014_alter_invitation_added_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qualification",
            old_name="date_issued",
            new_name="issued_on",
        ),
    ]
