# Generated by Django 4.2.5 on 2024-03-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0015_rename_date_issued_qualification_issued_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="issued_on",
            field=models.DateField(verbose_name="date issued"),
        ),
    ]
