# Generated by Django 4.2.5 on 2024-03-30 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0016_alter_qualification_issued_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="date_created",
            new_name="created_on",
        ),
    ]
