# Generated by Django 5.0.9 on 2024-11-17 21:22

from django.db import migrations, models

import cciw.officers.fields


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0017_rename_date_created_reference_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address_country",
            field=cciw.officers.fields.RequiredCharField(blank=True, max_length=100, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="application",
            name="address_county",
            field=cciw.officers.fields.RequiredCharField(blank=True, max_length=100, verbose_name="county"),
        ),
        migrations.AlterField(
            model_name="application",
            name="address_firstline",
            field=cciw.officers.fields.RequiredCharField(blank=True, max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="application",
            name="address_mobile",
            field=models.CharField(blank=True, max_length=30, verbose_name="mobile"),
        ),
        migrations.AlterField(
            model_name="application",
            name="address_tel",
            field=cciw.officers.fields.RequiredCharField(blank=True, max_length=30, verbose_name="telephone"),
        ),
        migrations.AlterField(
            model_name="application",
            name="birth_place",
            field=cciw.officers.fields.RequiredCharField(blank=True, max_length=100, verbose_name="place of birth"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="mobile",
            field=models.CharField(blank=True, max_length=30, verbose_name="mobile"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="tel",
            field=models.CharField(blank=True, max_length=30, verbose_name="telephone"),
        ),
    ]
