# Generated by Django 5.0.9 on 2025-04-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0018_alter_application_address_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="character",
            field=models.TextField(
                verbose_name="Please comment on aspects of the applicant's character (ie. Christian experience honesty, trustworthiness, reliability, disposition, faithful attendance at worship/prayer meetings.)"
            ),
        ),
    ]
