# Generated by Django 6.0.1 on 2026-01-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0019_alter_reference_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="previous_reference",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="following_references",
                to="officers.reference",
            ),
        ),
    ]
