# Generated by Django 6.0.1 on 2026-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officers", "0020_reference_previous_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceaction",
            name="bounced_email",
            field=models.CharField(blank="", default=""),
        ),
        migrations.AlterField(
            model_name="referenceaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("requested", "Reference requested"),
                    ("received", "Reference received"),
                    ("filledin", "Reference filled in manually"),
                    ("nag", "Applicant nagged"),
                    ("detailscorrected", "Referee details corrected"),
                    ("requestbounced", "Email to referee bounced"),
                ],
                max_length=20,
            ),
        ),
    ]
