# Generated by Django 6.0.5 on 2026-08-08 15:27

from django.conf import settings
from django.db import migrations

import cciw.officers.fields
import cciw.officers.models.references


class Migration(migrations.Migration):
    dependencies = [
        ("cciwmain", "0003_alter_campname_options"),
        ("officers", "0021_referenceaction_bounced_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="name",
            field=cciw.officers.fields.RequiredCharField(
                blank=True,
                help_text="Name only - please do not include job title or other information.",
                max_length=100,
                validators=[cciw.officers.models.references.no_titles],
                verbose_name="Name",
            ),
        ),
    ]
