# Generated by Django 6.0.5 on 2026-08-08 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cciwmain", "0003_alter_campname_options"),
        ("officers", "0022_alter_referee_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("DataRelatedToCampersYear", "DataRelatedToCampersYear"),
                            (
                                "DataRelatedToCampersOnCamp",
                                "DataRelatedToCampersOnCamp",
                            ),
                            (
                                "DataRelatedToOfficersOnCamp",
                                "DataRelatedToOfficersOnCamp",
                            ),
                        ]
                    ),
                ),
                ("filename", models.CharField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "camp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_download_logs",
                        to="cciwmain.camp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_download_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
