# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0027_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['application', 'type__name']},
        ),
        migrations.AlterField(
            model_name='qualificationtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('application', 'type')},
        ),
    ]
