# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:40
from __future__ import unicode_literals

import cciw.officers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0030_application_crb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='crb_check_consent',
            field=cciw.officers.fields.ExplicitBooleanField(default=None, verbose_name='Do you consent to the obtaining of a Disclosure and Barring Service check on yourself? '),
        ),
        migrations.AlterField(
            model_name='application',
            name='crb_number',
            field=models.CharField(blank=True, default='', help_text='Current enhanced DBS number with update service', max_length=128, verbose_name='DBS number'),
        ),
    ]
