# Generated by Django 1.10.5 on 2017-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0031_auto_20170303_1040"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CRBApplication",
            new_name="DBSCheck",
        ),
    ]
