# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0035_auto_20170303_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbscheck',
            name='check_type',
            field=models.CharField(choices=[('form', 'Full form'), ('online', 'Online check')], default='form', max_length=20, verbose_name='check type'),
        ),
    ]
