# Generated by Django 1.10.5 on 2017-03-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0037_auto_20170303_2128"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DBSFormLog",
            new_name="DBSActionLog",
        ),
    ]
