# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0038_auto_20170304_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsactionlog',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbsactionlogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
