# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:02
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0043_dbsactionlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsactionlog',
            name='action_type',
            field=models.CharField(choices=[('form_sent', 'DBS form sent'), ('leader_alert_sent', 'Alert sent to leader')], max_length=20, verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='dbsactionlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
