# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0044_auto_20170304_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbsactionlog',
            options={'verbose_name': 'DBS action log', 'verbose_name_plural': 'DBS action logs'},
        ),
    ]
