# Generated by Django 2.1.11 on 2019-12-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0056_auto_20190801_2018"),
        ("officers", "0056_auto_20191208_1916"),
    ]

    operations = []
