# Generated by Django 2.2.7 on 2020-03-01 14:05

import cciw.officers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0057_merge_20191211_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='capacity_known',
            field=cciw.officers.fields.RequiredCharField(blank=True, help_text='In what capacity does the referee know you? (see above)', max_length=255, verbose_name='Capacity known'),
        ),
    ]
