# Generated by Django 3.1.7 on 2021-05-06 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0062_auto_20210412_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceaction',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='referenceaction',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='dbsactionlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='dbsactionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
