# Generated by Django 3.2.6 on 2021-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0064_auto_20210818_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="given_in_confidence",
            field=models.BooleanField(
                default=False,
                help_text='Is this reference given "in confidence"? If yes, in the case that the applicant wishes to see the contents of the references made about them under a GDPR "Right of access" request, we will exclude the contents of this reference. It is important to us that you feel at liberty to tell us any concerns you have about the applicant, so you may tick this box if you feel it is necessary.',
            ),
        ),
    ]
