# Generated by Django 3.1.7 on 2021-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20210403_1923"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="erased_on",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
