# Generated by Django 3.1.7 on 2021-04-11 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_erased_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="allow_emails_from_public",
            field=models.BooleanField(
                default=False,
                help_text="If unchecked, the email address will be a group communication list, usable only by other members of the list.",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="email",
            field=models.EmailField(blank=True, help_text="Email address including domain. Optional.", max_length=254),
        ),
        migrations.AlterField(
            model_name="role",
            name="email_recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text='This defines which users will be emailed for email sent to the role email address above. Usually the same as "members", or a subset, but could have additional people.',
                related_name="roles_as_email_recipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="members",
            field=models.ManyToManyField(
                help_text="This defines which users have access rights to all the functionality on the website related to this role. ",
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
