# Generated by Django 4.2.5 on 2024-03-30 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="erased_on",
            new_name="erased_at",
        ),
    ]
