# Generated by Django 4.2.5 on 2024-03-30 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_erased_on_user_erased_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="joined_at",
        ),
    ]
