# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20150814_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_member',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_member',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personalaward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='personalaward',
            name='member',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='last_post_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='post',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_post_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='news_item',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='started_by',
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='member',
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='poll_option',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PersonalAward',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='VoteInfo',
        ),
    ]
