# Generated by Django 4.2.5 on 2024-01-09 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_retention", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="erasureexecutionlog",
            options={"ordering": ["executed_at"]},
        ),
    ]
