# This file defines various important roles and the permissions to be given to
# them in the 'admin' section of the website.
#
# Roles work in two ways:
#
# - We have statically defined roles, defined in the this file. People are added
#   to these roles by a superuser, using the admin section.
#
# - We also have 'dynamic' roles which are calculated automatically using other
#   data in the database. For example, via the links between the 'Camp',
#   'Person' and 'User' table, we know which logged in 'Users' are leaders for
#   camps, and which are leaders for current camps. These are 'current leaders',
#
# Permissions work in two ways:
#
# - The permissions defined in this file that allow certain roles to view/edit
#   various database tables via the 'admin' section of the website.
#
# - Certain other pages (e.g. booking reports, leaders functionality) are
#   limited to certain roles (dynamic or static). These are hard-coded in the
#   relevant parts of the source code.
#
# So this file covers only part of our permissions mechanism.
#
# This file is used by automated tests, and is applied to the production
# database as part of the deployment procedure, ensuring that each group exists
# and has all and only the permissions specified here.
#
# The contents need to be agreed with the CCiW committee, as per the "CCiW
# website security procedures" document.
#
# The names of the roles need to be synced with /cciw/accounts/models.py
#
# Format of permissions is: app name/table name/permission
#    where:
#      app name: refers to a sub section of the website (officers, bookings etc)
#      table: a name of a database table
#      permission: 'add', 'view', 'change', or 'delete'
#
# Where 'change' permission is present, 'view' is implied and doesn't
# need to be specified.

Roles:
  Secretaries:
    Permissions:
      # Need to be able to view officer applications
      - officers/application/view
      - officers/qualificationtype/view
  Booking secretaries:
    Permissions:
      # Need to be able to add and change bookings and their accounts
      - bookings/booking/add
      - bookings/booking/change
      - bookings/booking/delete
      - bookings/bookingaccount/add
      - bookings/bookingaccount/change
      - bookings/bookingaccount/delete
      # Need to be able to record manual payments, refunds and transfers
      - bookings/manualpayment/add
      - bookings/manualpayment/change
      - bookings/manualpayment/delete
      - bookings/accounttransferpayment/add
      - bookings/accounttransferpayment/change
      - bookings/accounttransferpayment/delete
      - bookings/refundpayment/add
      - bookings/refundpayment/change
      - bookings/refundpayment/delete
      # In order to view payment inlines, need this:
      - bookings/payment/view
      # Helpful for them to be able to manage prices
      - bookings/price/add
      - bookings/price/change
      - bookings/price/delete
      # To be able to change number of bookings allowed, they can edit camps
      - cciwmain/camp/change
  DBS Officers:
    Permissions:
      - officers/dbscheck/add
      - officers/dbscheck/change
      - officers/dbscheck/delete
      - officers/dbsactionlog/add
      - officers/dbsactionlog/change
      - officers/dbsactionlog/delete
  Committee:
    Permissions:
      # Do general changes to camps, including setting leaders
      - cciwmain/camp/change
      - cciwmain/person/change
      # Need to be able to view/manage application forms
      - officers/application/change
      - officers/qualificationtype/add
      - officers/qualificationtype/change
      - officers/qualificationtype/delete
      # View references
      - officers/reference/change
  Chairperson:
    # This person will be a member of Committee as well. They additionally have
    # the rights to change User, which is effectively superuser rights. To avoid
    # giving this to too many users who will not understand that they have it,
    # this permission is separated out.
    Permissions:
      - accounts/user/change
  Site editors:
    # People with general permissions to manage the
    # site - enter camp information etc.
    Permissions:
      - cciwmain/camp/add
      - cciwmain/camp/change
      - cciwmain/camp/delete
      - cciwmain/campname/add
      - cciwmain/campname/change
      - cciwmain/campname/delete
      - cciwmain/person/add
      - cciwmain/person/change
      - cciwmain/person/delete
      - cciwmain/site/add
      - cciwmain/site/change
      - cciwmain/site/delete
      - sitecontent/htmlchunk/add
      - sitecontent/htmlchunk/change
      - sitecontent/htmlchunk/delete
      - sitecontent/menulink/add
      - sitecontent/menulink/change
      - sitecontent/menulink/delete
  Safeguarding co-ordinators:
    # No admin permisssions needed
    Permissions: []
  Wiki users:
    # No admin permisssions needed
    Permissions: []
