# This file defines various important roles and the permissions to be given to
# them in the 'admin' section of the website.
#
# Roles work in two ways:
#
# - We have statically defined roles, defined in the this file. People are added
#   to these roles by a superuser, using the admin section.
#
# - We also have 'dynamic' roles which are calculated automatically using other
#   data in the database. For example, via the links between the 'Camp',
#   'Person' and 'User' table, we know which logged in 'Users' are leaders for
#   camps, and which are leaders for current camps. These are 'current leaders'.
#   This type of role does not need to manually managed.
#
# Permissions work in two ways:
#
# - The permissions defined in this file allow certain roles to view/edit
#   various database tables via the 'admin' section of the website.
#
# - Certain other pages (e.g. booking reports, leaders functionality) are
#   limited to certain roles (dynamic or static). These are hard-coded in the
#   relevant parts of the source code.
#
# So this file covers only part of our permissions mechanism.
#
# This file is used by automated tests, and is applied to the production
# database as part of the deployment procedure, ensuring that each group exists
# and has all and only the permissions specified here.
#
# The contents need to be agreed with the CCiW committee, as per the "CCiW
# website security procedures" document, which contains further important info
# about access rights for certain people.
#
# The names of the roles need to be synced with /cciw/accounts/models.py
#
# Format of permissions is: app name.table name/permission
#    where:
#      app name: refers to a sub section of the website (officers, bookings etc)
#      table: a name of a database table
#      permission: 'add', 'view', 'change', or 'delete'
#
# Where 'change' permission is present, 'view' is implied and doesn't
# need to be specified.

Roles:
  Secretaries:
    Permissions:
      # Need to be able to view officer applications
      - officers.Application/view
      - officers.QualificationType/view
  Booking secretaries:
    Permissions:
      # Need to be able to add and change bookings and their accounts
      - bookings.Booking/add
      - bookings.Booking/change
      - bookings.Booking/delete
      - bookings.BookingAccount/add
      - bookings.BookingAccount/change
      - bookings.BookingAccount/delete
      # - "Supporting information" is used for bookings
      #   that requires extra evidence of suitablility of camper
      #   or regarding requests for discounts.
      - bookings.SupportingInformation/add
      - bookings.SupportingInformation/change
      - bookings.SupportingInformation/delete
      - bookings.SupportingInformationType/add
      - bookings.SupportingInformationType/change
      - bookings.SupportingInformationType/delete
      - bookings.SupportingInformationDocument/delete
      - bookings.SupportingInformationDocument/view
      # Need to be able to record manual payments, refunds and transfers
      - bookings.ManualPayment/add
      - bookings.ManualPayment/change
      - bookings.ManualPayment/delete
      - bookings.AccountTransferPayment/add
      - bookings.AccountTransferPayment/change
      - bookings.AccountTransferPayment/delete
      - bookings.RefundPayment/add
      - bookings.RefundPayment/change
      - bookings.RefundPayment/delete
      - bookings.WriteOffDebt/add
      - bookings.WriteOffDebt/change
      - bookings.WriteOffDebt/delete
      # In order to view payment inlines, need this:
      - bookings.Payment/view
      # Helpful for them to be able to manage prices
      - bookings.Price/add
      - bookings.Price/change
      - bookings.Price/delete
      # To be able to change number of bookings allowed, they can edit camps
      - cciwmain.Camp/change
  DBS Officers:
    Permissions:
      - officers.DBSCheck/add
      - officers.DBSCheck/change
      - officers.DBSCheck/delete
      - officers.DBSActionLog/add
      - officers.DBSActionLog/change
      - officers.DBSActionLog/delete
  Committee:
    Permissions:
      # Do general changes to camps, including setting leaders
      - cciwmain.Camp/change
      - cciwmain.Person/change
      # Need to be able to view/manage application forms
      - officers.Application/change
      - officers.QualificationType/add
      - officers.QualificationType/change
      - officers.QualificationType/delete
      # View references
      - officers.Reference/change
  Chairperson:
    # This person will be a member of Committee as well
    Permissions: []
  Site editors:
    # People with general permissions to manage the
    # site - enter camp information etc.
    Permissions:
      - cciwmain.Camp/add
      - cciwmain.Camp/change
      - cciwmain.Camp/delete
      - cciwmain.CampName/add
      - cciwmain.CampName/change
      - cciwmain.CampName/delete
      - cciwmain.Person/add
      - cciwmain.Person/change
      - cciwmain.Person/delete
      - cciwmain.Site/add
      - cciwmain.Site/change
      - cciwmain.Site/delete
      - sitecontent.HtmlChunk/add
      - sitecontent.HtmlChunk/change
      - sitecontent.HtmlChunk/delete
      - sitecontent.MenuLink/add
      - sitecontent.MenuLink/change
      - sitecontent.MenuLink/delete
  Safeguarding co-ordinators:
    # No admin permisssions needed
    Permissions: []
  Wiki users:
    # No admin permisssions needed
    Permissions: []
  Webmasters:
    # Have superuser rights
    Permissions: []
  Debug:
    # For debugging email lists
    Permissions: []
