# Generated by Django 4.2.3 on 2023-09-13 19:09

from django.db import migrations


def forwards(apps, schema_editor):
    HtmlChunk = apps.get_model("sitecontent", "HtmlChunk")
    HtmlChunk.objects.get_or_create(name="donate_intro")
    HtmlChunk.objects.get_or_create(name="donate_outro")


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards, lambda *args, **kwargs: None)]
