# Generated by Django 4.2.5 on 2024-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0002_create_donate_htmlchunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="htmlchunk",
            name="id",
            field=models.BigIntegerField(null=True),
        ),
    ]
