# Generated by Django 4.2.5 on 2024-01-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0004_populate_htmlchunk_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlchunk",
            name="id",
            field=models.BigIntegerField(),
        ),
    ]
