# Generated by Django 4.2.5 on 2024-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0006_alter_htmlchunk_id_alter_htmlchunk_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlchunk",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
