# Generated by Django 4.2.5 on 2024-01-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0007_alter_htmlchunk_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlchunk",
            name="name",
            field=models.SlugField(unique=True, verbose_name="name"),
        ),
    ]
