# Generated by Django 4.2.5 on 2024-01-09 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0008_alter_htmlchunk_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="htmlchunk",
            options={"ordering": ["name"], "verbose_name": "HTML chunk"},
        ),
    ]
