# Generated by Django 3.0.6 on 2020-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_emailforward"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailforward",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
