# Generated by Django 3.0.6 on 2020-12-16 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0004_emailforward_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailforward',
            name='address',
            field=models.EmailField(help_text='Email address including domain', max_length=254),
        ),
        migrations.RemoveField(
            model_name='emailforward',
            name='recipients',
        ),
        migrations.AddField(
            model_name='emailforward',
            name='recipients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
