# Generated by Django 3.0.6 on 2020-12-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_auto_20201216_0844"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailForward",
        ),
    ]
