# Generated by Django 6.0.5 on 2026-08-10 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mail", "0001_initial_squashed_0007_delete_emailforward"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMailRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_id", models.CharField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("sent_count", models.IntegerField(default=0)),
            ],
        ),
    ]
