# Generated by Django 4.2.5 on 2024-05-18 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cciwmain", "0002_camp_officers"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_name", models.CharField(max_length=1024, verbose_name="name of guest")),
                ("arrived_on", models.DateField()),
                ("left_on", models.DateField()),
                ("purpose_of_visit", models.TextField()),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("remote_addr", models.GenericIPAddressField()),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="visitor_logs", to="cciwmain.camp"
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
